In [4]:
%matplotlib inline

import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt

import pandas as pd
import statsmodels.formula.api as sm
from sklearn.linear_model import LinearRegression

## 1.20

a. 
$\hat Y =  − 0.580 + 15.0352X$

b. 
![Plot of regression Y =  − 0.580 + 15.0352X](files/plot20.png)

It's a good fit. The Pearson correlation coefficient is 0.979. 

c. $b_0$ would be the time taken to service 0 copiers, which is meaningless.

d.

In [3]:
-0.580+15.0352*5

74.596

$\hat Y(5)$ = 74.60 minutes

## 1.24

a. 
I'm following along with http://connor-johnson.com/2014/02/18/linear-regression-with-python/.

In [9]:
df24 = pd.read_table('/Users/kevin/Dropbox/School/STA-580/ch1hw/Ch1-20.csv', sep=',', index_col=False)
df24['Eins'] = np.ones(( len(df24), ))
df24

    time  copiers  Eins
0     20        2     1
1     60        4     1
2     46        3     1
3     41        2     1
4     12        1     1
5    137       10     1
6     68        5     1
7     89        5     1
8      4        1     1
9     32        2     1
10   144        9     1
11   156       10     1
12    93        6     1
13    36        3     1
14    72        4     1
15   100        8     1
16   105        7     1
17   131        8     1
18   127       10     1
19    57        4     1
20    66        5     1
21   101        7     1
22   109        7     1
23    74        5     1
24   134        9     1
25   112        7     1
26    18        2     1
27    73        5     1
28   111        7     1
29    96        6     1
30   123        8     1
31    90        5     1
32    20        2     1
33    28        2     1
34     3        1     1
35    57        4     1
36    86        5     1
37   132        9     1
38   112        7     1
39    27        1     1
40   131        9     1
41    34        2     1
42    27        2     1
43    61        4     1
44    77        5     1

In [12]:
y24 = df24.time
x24 = df24[['copiers', 'Eins']]
result24 = sm.OLS(y24, x24).fit()
result24.summary()
# residuals
result24.resid

0     -9.490339
1      0.439164
2      1.474413
3     11.509661
4     -2.455091
5    -12.772324
6     -6.596084
7     14.403916
8    -10.455091
9      2.509661
10     9.262924
11     6.227676
12     3.368668
13    -8.525587
14    12.439164
15   -19.701828
16     0.333420
17    11.298172
18   -22.772324
19    -2.560836
20    -8.596084
21    -3.666580
22     4.333420
23    -0.596084
24    -0.737076
25     7.333420
26   -11.490339
27    -1.596084
28     6.333420
29     6.368668
30     3.298172
31    15.403916
32    -9.490339
33    -1.490339
34   -11.455091
35    -2.560836
36    11.403916
37    -2.737076
38     7.333420
39    12.544909
40    -3.737076
41     4.509661
42    -2.490339
43     1.439164
44     2.403916
dtype: float64

In [13]:
# sum of squared residuals
result24.ssr

3416.377023498696